agent:
  name: "edr-agent-test"
  version: "1.0.0"
  environment: "development"
  data_dir: "/tmp/edr"
  pid_file: "/tmp/edr-agent.pid"
  interval: "30s"

logging:
  level: "info"
  format: "console"
  output: "stdout"

monitoring:
  process:
    enabled: true
    interval: "3s"
    buffer_size: 100
    whitelist: []
    blacklist:
      - "kthreadd"
      - "ksoftirqd"
      - "migration" 